### ISSUE TITLE
[BUG] Rotting logs in Mort Myre sometimes cannot be picked.

### ISSUE THREAD

**Issue by DevinDuBose** [DarkanRS/world-server#115]
**Describe the bug**
Sometimes the logs become unpickable. Likely due to how the objects have their IDs set. I think it is spawning a new object or something when the player picks the fungus instead of setting the ID.

**To Reproduce**
bloom, pick, bloom, pick, bloom, pick on repeat till it breaks.

**Expected behavior**
Game to work properly OMEGALUL.

**Additional context**
Need to add missing objects as well.

3508 - Rotting log [10] [null, null, null, null, null]
3509 - Fungi on log [10] [null, Pick, null, null, null]
3510 - Rotting branch [10] [null, null, null, null, null]
3511 - Budding branch [10] [null, Take-cutting, null, null, null]
3512 - A small bush [10] [null, null, null, null, null]
3513 - A golden pear bush [10] [null, Pick, null, null, null]

50718 - Rotting log [10] [null, null, null, null, null]
50736 - Fungi on log [10] [null, Pick, null, null, null]
50746 - Rotting log [10] [null, null, null, null, null]
50791 - Fungi on log [10] [null, Pick, null, null, null]

50838 - Rotting branch [10] [null, null, null, null, null]
50853 - Budding branch [10] [null, Take-cutting, null, null, null]
50895 - Rotting branch [10] [null, null, null, null, null]
50907 - Budding branch [10] [null, Take-cutting, null, null, null]

50984 - A small bush [10] [null, null, null, null, null]
51073 - A golden pear bush [10] [null, Pick, null, null, null]
51081 - A small bush [10] [null, null, null, null, null]
51088 - A golden pear bush [10] [null, Pick, null, null, null]

**Comment by JesseGuerrero** [comment]
I added some logs to the item list for blessed sickle, but have not fixed this bug
