### ISSUE TITLE
[BUG] File Not Found Exception when pulling the repo clean

### ISSUE THREAD

**Issue by tilkinsc** [DarkanRS/world-server#124]
**Describe the bug**
Internally the repository wants to find ..\darkan-cache\main_file_cache.dat2 (etc) and this appears to be hardcoded. So when you swapped over to DarkanRS/world-server from titandino/darkan-world-server it broke the directory hierarchy. This is because git wants to create the directory as 'world-server' instead of 'darkan-world-server' now.

**To Reproduce**
1. git clone everything to ./
2. run gradle or launch com.rs.Launcher.Main

**Expected behavior**
Cache file name should be reflected to match the current expected hierarchy.

**Screenshots**
![image](https://user-images.githubusercontent.com/7494772/152707663-783e3eb7-2f4f-490d-b813-eb2c73c49143.png)

**Additional context**
Perhaps the cache should be included inside the root of this directory, and you can add a git submodule. This will resolve future name changes if any, as per formally how git operates. User can now clone the cache directly with the world source in this set up.

**Comment by titandino** [comment]
Fixed
