### ISSUE TITLE
[BUG] Soft-locking account progress on tutorial island by burning bread

### ISSUE THREAD

**Issue by Nevior** [DarkanRS/world-server#145]
**Describe the bug**
Cannot proceed on a new character if you burn the bread dough given to you by Master chef. Dialogue tells you to talk to him to replace but he doesn't replace, the game just soft-locks. 

**To Reproduce**
1: Combine water and flour to make dough
2: Attempt to cook dough
3: Burn dough and be told to talk to "Lev" for replacement
4: Talk to Master chef and use each and every dialogue option only to discover none of them give you more dough or supplies
5: Cry a little bit and re-roll a new character and hope you don't burn it lmao

**Expected behavior**
Give replacement dough or don't give a chance to burn the bread.

**Screenshots**
https://i.gyazo.com/9cc2f69bf107847ed9ca391116c3b083.jpg

**Additional context**
Bread burnt.

**Comment by titandino** [comment]
Fixed
