### ISSUE TITLE
[BUG] Player can agro other mobs while projectile is in air

### ISSUE THREAD

**Issue by tilkinsc** [DarkanRS/world-server#427]
**Describe the bug**
While fighting abberrant sprecters in slayer tower I was able to attack one without it attacking me back after a kill while a different a projectile was in the air. The one agro'd onto me attacked me, and I attacked a different one, and the one I attacked didn't fight back because it couldn't. (single)

**To Reproduce**
1. Go to abberrant spectres on floor 2 of slayer tower
2. Click on abberrant specter after combat timer before projectile hits you

**Comment by titandino** [comment]
Fixed
