### ISSUE TITLE
Farming issues

### ISSUE THREAD

**Issue by DevinDuBose** [DarkanRS/world-server#76]
Cannot empty buckets
Lumbridge hops patch leprechaun does not work
Cannot plant evil turnip seeds
Picking cactus spines regresses the growth stage

**Comment by LazyCeleste** [comment]
Can't check health of calquat trees, once grown they only have the pick-fruit option

**Comment by DevinDuBose** [comment]
Cannot plant spirit weed seeds

**Comment by LazyCeleste** [comment]
Cannot rake the Draynor manor evil turnip patch
Cannot pick Draynor manor cabbages

**Comment by LazyCeleste** [comment]
Flower patches do not protect allotments like they should
