### ISSUE TITLE
Cutscene Manager

### ISSUE THREAD

**Issue by JesseGuerrero** [DarkanRS/world-server#91]
**Cutscene Music control**
At the moment when entering the dragon slayer boat scene random music plays when teleported to the new region. We can either remove region music for cutscenes made by the manager or toggle ambient music, genre and music on enter region. like  controllers. Whichever you think is best, ill go with. :D
![image](https://user-images.githubusercontent.com/27308928/151041095-c0acab22-4980-4a6d-bb40-8ae22b75a8ef.png)

**Screen border change with resizeable**
Resizeable looks different...
![image](https://user-images.githubusercontent.com/27308928/151041665-760b3e6a-bd18-4e7a-9b3f-7f74a2d956b3.png)

I will be using the cutscene manager and adding more issues which pop up. But so far this is what I saw from the Dragon Slayer boat scene. After I finish learning the manager I will touch up the scene and add it into the quest then test.

**Comment by titandino** [comment]
I actually don't know the new music system you added well enough at the moment to implement that. I can check into the border change though. I remember resizeable looking like that in the real game for cutscenes though.
